import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Netflix Rebrand • Neo Cinema",
  description:
    "A modern Netflix website rebrand built using Next.js + Tailwind CSS with AI branding (Durable + Adobe Firefly) and Firebase dynamic content.",
  keywords: [
    "Netflix Rebrand",
    "Next.js",
    "Tailwind CSS",
    "Firebase",
    "Future Interns",
    "Full Stack Web Development",
  ],
  openGraph: {
    title: "Netflix Rebrand • Neo Cinema",
    description:
      "Premium streaming platform UI rebrand with dynamic content using Firebase.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
